# SUBJECT APP CONFIG
# This is the subject application config
# store config here custom to this app and/or overrides of config in mdm-cuf-core-server.yml
#----------------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------------

#----------------------------------------------------------------------------------------------------------------------
# DEFAULT CONFIG
# The default config contains global configs that apply under all profiles, unless overridden (which should be rare).
#----------------------------------------------------------------------------------------------------------------------
spring: 
  profiles.include: MODE-MEMBER

# default port if running as a spring-boot app (not a deployed war) and not overriding    
server.port: 8081

mdm-cuf-person-adapter-vba-corp:
  demo-property: DEMO_PROPERTY 

# properties rendered in the /info endpoint
info.mdm-cuf-person-adapter-vba-corp-server:
    version:  "0.1-SNAPSHOT"
    artifact: "mdm-cuf-person-adapter-vba-corp-server"
    name: "mdm-cuf-person-adapter-vba-corp-server"
    description: "mdm-cuf-person-adapter-vba-corp Server War"
    
# note that a /logs folder off root may be required to exist on your local to run under tomcat
logging:
  file: logs/mdm-cuf-person-adapter-vba-corp/mdm-cuf-person-adapter-vba-corp.log
     
mdm-cuf: 
  instance-subject-name: PERSON
  instance-system-name: VBACORP

---
#----------------------------------------------------------------------------------------------------------------------
# ENV-LOCAL-DEV PROFILE
# The default profile, used for the local dev environment.
#----------------------------------------------------------------------------------------------------------------------
spring:
  profiles: ENV-LOCAL-DEV
---
#----------------------------------------------------------------------------------------------------------------------
# ENV-UNIT-TESTPROFILE
# Profile for UNIT Tests
#----------------------------------------------------------------------------------------------------------------------
spring:
  profiles: ENV-UNIT-TEST
  profiles.include: PARTNER-SIM
---
#----------------------------------------------------------------------------------------------------------------------
# ENV-CI-DEV PROFILE
# Profile for the highly controlled CI env where we run all checked in code integration tests against fully controlled infrastructure
#----------------------------------------------------------------------------------------------------------------------
spring:
  profiles: ENV-CI-DEV
  profiles.include: PARTNER-SIM
    
mdm-cuf:
  multi-tenant-postfix: -DEV
  async.servers: kafka:9092
---
#----------------------------------------------------------------------------------------------------------------------
# ENV-CI-ALPHA PROFILE
# Profile for the highly controlled CI env where we run the first alpha release integration tests against fully controlled infrastructure
#----------------------------------------------------------------------------------------------------------------------
spring:
  profiles: ENV-CI-ALPHA
  profiles.include: PARTNER-SIM
    
mdm-cuf:
  multi-tenant-postfix: -ALPHA
  async.servers: kafka:9092 

